src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $begin_at;

    /**
     * @ORM\OneToOne(targetEntity=Media::class, inversedBy="formation", cascade={"persist", "remove"})
     */
    private $media;

    /**
     * @ORM\OneToMany(targetEntity=Inscription::class, mappedBy="formation")
     */
    private $inscriptions;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Poster;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prix;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBeginAt(): ?\DateTimeInterface
    {
        return $this->begin_at;
    }

    public function setBeginAt(\DateTimeInterface $begin_at): self
    {
        $this->begin_at = $begin_at;

        return $this;
    }

    public function getMedia(): ?Media
    {
        return $this->media;
    }

    public function setMedia(?Media $media): self
    {
        $this->media = $media;

        return $this;
    }

    /**
     * @return Collection|Inscription[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions[] = $inscription;
            $inscription->setFormation($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getFormation() === $this) {
                $inscription->setFormation(null);
            }
        }

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->Poster;
    }

    public function setPoster(string $Poster): self
    {
        $this->Poster = $Poster;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\FormationVideo;
use App\Repository\FormationVideoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
 *  @Route("/video")
 */
class VideoController extends AbstractController
{
    /**
     * @Route("", name="video")
     */
    public function index(FormationVideoRepository $repo): Response
    {
        return $this->render('video/index.html.twig', [
            'notif' => '',
            'videos'=> $repo->findAll(),
        ]);
    }
    /**
     * @Route("/view-{id}", name="video_view")
     */
    public function view(FormationVideo $video): Response
    {
        return $this->render('video/view.html.twig', [
            'notif' => '',
            'videos'=> $video
        ]);
    }
}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    videos Video
{% endblock %}

{% block body %}
	<div class='container'>
		<div class="row mt-2">
           {% include "video/listing.html.twig" %}
		</div>
	</div>
{% endblock %}

templates/video/listing.html.twig
  {% for video in videos %}
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <a href="#"><img class="card-img-top" src="{{ asset(video.poster) }}" alt="{{ video.titre }}"></a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="{{ path('video_view',{id:video.id}) }}">{{ video.titre }}</a>
        </h4>
        <h5>{{ video.prix |number_format(0,'.',' ') }} FCFA</h5>
        <p class="card-text">
          {% if video.description |length >70 %}
          {{ video.description |slice(0, 70)}} ...
          {% else %}
          {{ video.description}}
          {% endif %}
          
        </p>
      </div>
      <div class="card-footer">
        <small class="text-muted">
          {% for n in range(1, 5, 1) %}
			{% if n <= 3 %} &#9733; {% else %} &#9734; {% endif %} {% endfor %} </span>
        </small>
      </div>
    </div>
  </div>
      
  {% endfor %}

templates/video/view.html.twig
{% extends "base.html.twig" %}