src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sujet;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_read;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    public function setSujet(string $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(?bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }
}

src/Controller/Admin/AdminContactController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Contact;
use App\Repository\ContactRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/contact")
 */
class AdminContactController extends AbstractController
{
    private $cr;
    public function __construct( ContactRepository $cr )
    {
        $this->cr = $cr;
        
    }

    /**
     * @Route("/", name="admin_contact")
     */
    public function index(): Response
    {
        return $this->render('admin_contact/index.html.twig', [
            'contacts' => $this->cr->findAll(),
            'messages' => $this->cr->findNotRead()
        ]);
    }
    /**
     * @Route("/remove-{id}", name="admin_contact_remove")
     */
    public function remove(Contact $c): Response
    {
        if ($c) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($c);
            $em->flush();
        }
        return $this->redirectToRoute('admin_contact');
    }

    /**
     * @Route("/view-{id}", name="admin_contact_view")
     */
    public function view(Contact $c): Response
    {
       
       if (!$c->getIsRead()) {
            $c->setIsRead(true);
            $em = $this->getDoctrine()->getManager();
            $em->persist($c);
            $em->flush();
           # code...
       }
        return $this->render('admin_contact/view.html.twig', [
            'contact' => $c,
            'messages' => $this->cr->findNotRead()
        ]);
    }
}

templates/admin_contact/index.html.twig
{% extends "blank.admin.html.twig" %}

{% block body %}
<div class="card">
    <div class="card-body">
        <div class="card-title">
            <i class="fa fa-poll-h"></i>
            Description
        </div>
        <div class="card-text">
            Tous les demande de contact ou de services custome
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="card-text">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Email</th>
                        <th>Sujet</th>
                        <th>Message</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    {% for ct in contacts %}
                    <tr>
                        <td>{% if ct.isRead %}
                            <i class="fas fa-eye"></i>
                            {% else %}
                            <i class="fas fa-eye-slash"></i>
                        {% endif %}</td>
                        <td>{{ct.email}}</td>
                        <td>{{ct.sujet}}</td>
                        <td>
                            {% if ct.message|length > 50 %}
                                {{ct.message |slice(0, 50 )}} ...
                                {% else %}
                                {{ct.message}}
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ path('admin_contact_remove',{'id':ct.id}) }}" class="btn btn-danger btn-circle"
                                id="delete"><i class="fa fa-trash"></i></a>
                        <a href="{{ path('admin_contact_view',{'id':ct.id}) }}" class="btn btn-primary btn-circle "><i
                                class="fa fa-eye"></i></a>
                        </td>
                        {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/admin_contact/view.html.twig
{% extends "blank.admin.html.twig" %}

{% block body %}
<div class="card">
    <div class="card-body">
        <div class="card-title">
          <b>Email</b> : {{ contact.email }} <br>
          <b>Objet</b> :  {{ contact.sujet}}

        </div>
        <p>
            <b>Message :</b> <br>
            {{ contact.message}}
        </p>
    </div>
</div>
{% endblock %}